name: Netlify
docs: https://open-api.netlify.com
description: Netlify is a hosting service for the programmable web. It provides an API to handle atomic deploys of websites, manage form submissions, inject JavaScript snippets, and more.
logo: https://pipedream.com/s.v0/app_1w0hvd/logo/orig
categories: ["hosting", "deployment"]
get_current_user_endpoint: /api/v1/users/me

auth_schemes:
  # OAuth2
  - scheme_name: netlify_oauth2
    auth_mode: OAUTH2
    authorization_url: https://app.netlify.com/authorize
    token_url: https://api.netlify.com/oauth/token
    default_scopes: ["admin:read", "admin:write"]
    scope_separator: ','
    token_access_request_method: POST
    authorization_params:
      response_type: code
    token_params:
      grant_type: authorization_code
    proxy:
      base_url: "https://api.netlify.com/api/v1"
    fields:
      - name: base_url
        displayName: Base URL
        description: "The base URL for the Netlify API endpoint."
        type: string
        default: https://api.netlify.com/api/v1

  # API-Key
  - scheme_name: netlify_api_key
    auth_mode: API_KEY
    proxy:
      base_url: "https://api.netlify.com/api/v1"
      headers:
        Authorization: "Bearer {{api_key}}"
    fields:
      - name: api_key
        expected_from_customer: true
        displayName: API Key
        description: "The API key used to authenticate with the Netlify API."
        type: string
        required: true
      - name: base_url
        expected_from_customer: true
        displayName: Base URL
        description: "The base URL for the Netlify API endpoint."
        type: string
        required: false
        default: https://api.netlify.com/api/v1